title: Aquari
description:
email: myleschatman@gmail.com

baseurl: ""
url: ""
linkedin_username: "myleschatman"
github_username: "myleschatman"
twitter_username:
youtube_username: "MylesChatman"
google_plus_username: "+MylesChatman"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include: ['_pages']
exclude: [node_modules, gulpfile.js]

collections:
  - projects
  - snippets
